---
- hosts: webservers
  remote_user: root
  become: no

  tasks:
  - name: Add Unix Admins users
    user: name={{ ansible }} group=users groups=wheel

  - name: Allow wheel group to have passwordless sudo
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'

  - name: Add sudoers users to wheel group
    user: name=ansible groups=wheel append=yes state=present createhome=yes
    
