---
- name: Using the copy module
  hosts: webservers
  become: yes
  tasks:
    - name: Create devops group
      group:
        name: devops
        state: present

    - name: Create devops user
      user:
        name: devops
        group: devops

    - name: Give sudo access to devops user
      blockinfile:
        path: /etc/sudoers
        insertafter: 'root    ALL=(ALL)       ALL'
        block: |
          # Gives sudo access to the devops group
          %devops        ALL=(ALL)       NOPASSWD: ALL
